### ISSUE TITLE
I Can't comple your xcode project.

### ISSUE THREAD

**Issue by genosyde** [lmtanco/videoDelayLine#1]
I don't know how to compile with boost.
could you please give me your setting about boost and version infomation.
thanks.

**Comment by lmtanco** [comment]
Hi @genosyde - thanks for this!
I am now having the same issue - I was using boost 1.59.0 but have updated my Mac OS since and the project no longer compiles. 

I have clang version 7.0.0. I cannot find info on wether boost 1.59.0 supports this, but the boost 1.60 beta seems to support it (http://www.boost.org/users/history/version_1_60_0.html). I will try with this and let you know if it works for me. 

Cheers!

**Comment by genosyde** [comment]
Thanks for your reply and your kindness.
I've tried to solve our issue with version_1_60_0.
My result is fail.
So, now I'm looking for answer of this issue.
Please, reference this web page. I wish, it is useful to you.
https://cplusplusmusings.wordpress.com/2012/07/05/clang-and-standard-libraries-on-mac-os-x/#comments

the error is same to me.

/Users/genosyde/Downloads/Coding/ofFrameWork/of_v0.9.4_osx_release/addons/ofxOSXBoost-master/libs/boost/include/boost/intrusive/detail/mpl.hpp:39:27: error: no member named 'remove_pointer' in namespace 'boost::move_detail'
using boost::move_detail::remove_pointer;
      ~~~~~~~~~~~~~~~~~~~~^
/Users/genosyde/Downloads/Coding/ofFrameWork/of_v0.9.4_osx_release/addons/ofxOSXBoost-master/libs/boost/include/boost/intrusive/detail/mpl.hpp:40:27: error: no member named 'add_pointer' in namespace 'boost::move_detail'
using boost::move_detail::add_pointer;
      ~~~~~~~~~~~~~~~~~~~~^

**Comment by lmtanco** [comment]
Thanks again @genosyde, will do some research as soon as I can and get back to you.

**Comment by lmtanco** [comment]
Hi @genosyde, sorry I've taken ages to fix this. 
I have now managed to compile again the project using https://github.com/danoli3/ofxOSXBoost. 

What I did was:
1. I checked out https://github.com/danoli3/ofxOSXBoost to my openFrameworks addon directory. 
2. I changed the following line in my CoreOF.xconfig file: 

`//HEADER_BOOST = "$(OF_PATH)/libs/boost/include"`
`HEADER_BOOST = "$(OF_PATH)/addons/ofxOSXBoost/libs/boost/include"`

And I recompiled and it woked! The commit I did was to update my project files to those generated by the Project Generator in OF 0.9.3. 

Hope it works for you too!
Best, 
Luis.

**Comment by genosyde** [comment]
Dear, Luis
Thank you for your request.
I have been so busy time during a few monthes.
Foturenatlly, I think your post, 
I'm so glad to hear happy news that is your solution work for my problem.
Thank you so much and I'll try when I finish my business until next week.
